PATHS:
    Q_VALIDATION_SET_PATH: "./results/validation_set_random_1000.pickle"
    SCORE_VALIDATION_SET_PATH: "./results/validation_set_initial_1000.pickle"

TRAIN:
    BATCH_SIZE: 32
    GAMMA: 0.97
    TARGET_UPDATE: 10
    EPS_START: 1.0
    EPS_END: 0.05
    EPS_DECAY: 200
    REPLAY_MEMORY_SIZE: 10000
    LEARNING_RATE: 0.001
    NUM_EPISODES: 500

    SCHEDULER:
        GAMMA: 0.3
        INITIAL_PERFORMANCE_THRSH: 100
        PERFORMANCE_LEAP: 25
        EPISODES_SUCCESS_SEQUENCE: 3
        COOLDOWN: 10

    VALIDATION:
        Q_VALIDATION_FREQUENCY: 10
        SCORE_VALIDATION_FREQUENCY: 50
        SCORE_VALIDATION_SIZE: 10

    CKPT_SAVE_DIR: "./results/checkpoints"
    CKPT_SAVE_FREQ: 1000
    CKPT_PATH: ""


    LOG:
        OUTPUT_DIR: "./results"

    VISUALIZE: True
